### ISSUE TITLE
Add more functionality to `cv.database`

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/echemdb#24]
The ' cv.databse'  could be extended with the following functionality.

- [ ] `save`: saves the current entries of, e.g., a filtered database as datapackages into a specific folder.
- [ ] `load`: load datapackages from a source, e.g., produced by `save`.
- [ ] `plot`: plot all entries of that database in a single plot (maybe ask if the number of entries exceeds ten). Allow direct comparson of CVs.
- [ ] `materials`: list of materials used (Added in #20 )
- [ ] `material`: (from #23 ) Return filter() with a predicate that filters by electrodes.counterelectrode.material==value. Not sure what is relevant in practice but we should provide all kinds of methods like this for what we and others typically want to search for.
- [ ] `describe`: Statistics about the database. partly addressed in #20. More discussion in #22 .
